#!/usr/bin/env python3

MIN_SITES = 10000
STEP = MIN_SITES
MAX_SITES = 50000
K = 512
MIN_THREADS = 1
MAX_THREADS = 32
THREAD_FACTOR = 2
WEAK_SCALING_SITES_PER_CORE = STEP
STRONG_SCALING_NUM_SITES = MAX_SITES

MSACONVERTER_BIN = "."
JUDICIOUS_BIN = "../build"
SUPERMATRIX_DIR = "."
TREEFILE_DIR = "."
PARTITIONS_DIR = "partitions-files"
REPEATS_DIR = "repeats-files"
