#!/usr/bin/env python3

MIN_SITES = 10000
STEP = MIN_SITES
MAX_SITES = 50000
K = 160
STRONG_SCALING_NUM_SITES = MAX_SITES

MSACONVERTER_BIN = "."
JUDICIOUS_BIN = "../build"
SUPERMATRIX_DIR = "."
TREEFILE_DIR = "."
PARTITIONS_DIR = "partitions-files"
REPEATS_DIR = "repeats-files"
