#!/usr/bin/env python3

MIN_SITES = 10000
STEP = MIN_SITES
MAX_SITES = 400000
K = 128
MIN_THREADS = 1
MAX_THREADS = 32
WEAK_SCALING_SITES_PER_CORE = MAX_SITES / MAX_THREADS
STRONG_SCALING_NUM_SITES = MAX_SITES

MSACONVERTER_BIN = "."
JUDICIOUS_BIN = "../build"
SUPERMATRIX_DIR = "."
TREEFILE_DIR = "."
PARTITIONS_DIR = "partitions-files"
REPEATS_DIR = "repeats-files"
